server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/song-service/**
          filters:
            - RewritePath=/song-service/(?<path>.*), /${path}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
            - Path=/user/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /${path}
        - id: oauth2-service
          uri: lb://user-service
          predicates:
            - Path=/oauth2/**
        - id: oauth2-redirect
          uri: lb://user-service
          predicates:
            - Path=/login/oauth2/code/**
        - id: playlist-service
          uri: lb://playlist-service
          predicates:
            - Path=/playlist-service/**
          filters:
            - RewritePath=/playlist-service/(?<path>.*), /${path}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
