# api-gateway/src/main/resources/application.yml
server:
  port: 8080

spring:
#  application:
#    name: api-gateway
#  config:
#    import: "optional:configserver:"
  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.web: DEBUG
