server:
  port: 0

spring:
#  application:
#    name: order-service
#  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: true
#  config:
#    import: "configserver:"
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
