server:
  port: 8080
spring:
#  application:
#    name: user-service
#  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: true
#  config:
#    import: "optional:configserver:"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liBrnhOnwu6hBnIP
            client-secret: 68d9c8bc706e9bf658895b856f8e8621081dfcd3

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    non-secure-port: 8080
    prefer-ip-address: true

